"""empty message

Revision ID: 3940f48be3db
Revises: 98e9c8aa2043
Create Date: 2020-05-21 22:00:24.407486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3940f48be3db'
down_revision = '98e9c8aa2043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('path', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_video_path'), 'video', ['path'], unique=True)
    op.drop_index('ix_video_url', table_name='video')
    op.drop_column('video', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('url', mysql.VARCHAR(length=120), nullable=True))
    op.create_index('ix_video_url', 'video', ['url'], unique=True)
    op.drop_index(op.f('ix_video_path'), table_name='video')
    op.drop_column('video', 'path')
    # ### end Alembic commands ###
