"""empty message

Revision ID: 4b5ec3b176e1
Revises: 3940f48be3db
Create Date: 2020-05-24 17:32:22.424009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5ec3b176e1'
down_revision = '3940f48be3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('num_reactions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'num_reactions')
    # ### end Alembic commands ###
