"""empty message

Revision ID: 98e9c8aa2043
Revises: f171df803fe6
Create Date: 2020-05-21 20:03:37.603278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e9c8aa2043'
down_revision = 'f171df803fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('reaction_stats', sa.Text(length=16000000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'reaction_stats')
    # ### end Alembic commands ###
