"""empty message

Revision ID: a91e340337db
Revises: 474794eae89f
Create Date: 2020-07-14 21:09:12.764963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91e340337db'
down_revision = '474794eae89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction', sa.Column('emoji_reaction', sa.Text(length=16000000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reaction', 'emoji_reaction')
    # ### end Alembic commands ###
